Updates to drivetrain
Creekside-Robotics/SwerveBot pull request #14
Opened 2022-11-21 01:33 UTC by josephhadad05

Adding necessary functionality to drivetrain

2022-11-21 14:55 UTC, paulelliott requested changes

2022-11-21 14:55 UTC, paulelliott commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        var modules = new ArrayList<SwerveModule>();
You can tighten the code in this method up quite a bit by declaring the `modules` array with values instead of adding them all individually. [Here's an article](https://www.java67.com/2015/10/how-to-declare-arraylist-with-values-in-java.html) that talks about how to do it. For your purposes the `List<ServeModule>` format to declare with values on one line will do the trick.

2022-11-21 14:55 UTC, paulelliott commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        modules.forEach((module) -> {
You can use `.stream().map(module -> module.getState())` to combine the `states` declaration and the iteration into a single line. This is a very common pattern in professional projects. It gets into some functional programming, which you'll run into a lot no matter what language you're working in.

Here's [an SO post](https://stackoverflow.com/questions/28319064/java-8-best-way-to-transform-a-list-map-or-foreach) that talks about it a bit.

2022-11-22 01:44 UTC, josephhadad05 commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        var modules = new ArrayList<SwerveModule>();
Thanks for the suggestion!

2022-11-22 02:59 UTC, josephhadad05 commented
closes #8

2022-11-22 18:13 UTC, paulelliott approved these changes

2022-11-22 18:30 UTC, merged